name: Events exercices

on:
  workflow_dispatch:

  push:
    branches:
      # - 'dev'
      # - 'feat*'
      #  push on any branch except "staging"
      - '!staging'
  pull_request:
  schedule:
    # Every minutes
    - cron: '*/1 * * * *'
    # Every Tuesday at 3am
    - cron: '0 3 * * 2'

jobs:
  print-event:
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)