name: second
on:
  workflow_run:
    workflows: ["first"]
    types:
      - completed
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
        ## get variable from first workflow
      - name: Get the event payload
        id: event
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const event = context.payload.workflow_run
            return event